"""initial

Revision ID: 576b8500d9f5
Revises: 
Create Date: 2026-01-09 18:06:05.864110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '576b8500d9f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fqdn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_fqdn'), 'site', ['fqdn'], unique=True)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status_code', sa.Enum('MOVED_PERMANENTLY', 'FOUND', 'SEE_OTHER', 'PERMANENT_REDIRECT', name='tokenstatus'), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'token', name='uix_site_id_token')
    )
    op.create_index(op.f('ix_token_site_id'), 'token', ['site_id'], unique=False)
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_index(op.f('ix_token_site_id'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_site_fqdn'), table_name='site')
    op.drop_table('site')
    # ### end Alembic commands ###
