"""rename_user

Revision ID: aaac9ba59e81
Revises: 99c7bdb41ddb
Create Date: 2026-03-04 22:19:04.747847

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aaac9ba59e81'
down_revision: Union[str, Sequence[str], None] = '99c7bdb41ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'sc_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('sc_user', 'user')
    # ### end Alembic commands ###
